services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: atalanta-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./storage:/var/www/storage
      - ./bootstrap/cache:/var/www/bootstrap/cache
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - DB_HOST=mysql
      - DB_DATABASE=atalanta_local
      - DB_USERNAME=atalanta
      - DB_PASSWORD=password
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - QUEUE_CONNECTION=redis
      - CACHE_DRIVER=redis
      - SESSION_DRIVER=redis
    depends_on:
      - mysql
      - redis
    networks:
      - atalanta-network

  nginx:
    image: nginx:alpine
    container_name: atalanta-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./storage/app/public:/var/www/storage/app/public
    depends_on:
      - app
    networks:
      - atalanta-network

  mysql:
    image: mysql:8.0
    container_name: atalanta-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: atalanta
      MYSQL_USER: atalanta
      MYSQL_PASSWORD: atalanta_password
      MYSQL_ROOT_PASSWORD: root_password
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - atalanta-network

  redis:
    image: redis:7-alpine
    container_name: atalanta-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - atalanta-network

  queue:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: atalanta-queue
    restart: unless-stopped
    command: php artisan queue:work --tries=3 --timeout=60
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./storage:/var/www/storage
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - DB_HOST=mysql
      - DB_DATABASE=atalanta
      - DB_USERNAME=atalanta
      - DB_PASSWORD=atalanta_password
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - QUEUE_CONNECTION=redis
    depends_on:
      - mysql
      - redis
      - app
    networks:
      - atalanta-network

  scheduler:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: atalanta-scheduler
    restart: unless-stopped
    command: sh -c "while true; do php artisan schedule:run --verbose --no-interaction; sleep 60; done"
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./storage:/var/www/storage
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - DB_HOST=mysql
      - DB_DATABASE=atalanta
      - DB_USERNAME=atalanta
      - DB_PASSWORD=atalanta_password
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - mysql
      - redis
      - app
    networks:
      - atalanta-network

volumes:
  mysql_data:
  redis_data:

networks:
  atalanta-network:
    driver: bridge 
