version: '3.8'

services:
  app:
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
    volumes:
      - ./:/var/www:cached
      - /var/www/vendor
      - /var/www/node_modules

  nginx:
    ports:
      - "8080:80"

  mysql:
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: atalanta_local
      MYSQL_USER: atalanta
      MYSQL_PASSWORD: password

  redis:
    ports:
      - "6380:6379" 